name: Deploy Medical Docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: sdk/medical-docs

      - name: Install dependencies
        run: |
          cd sdk/medical-docs
          npm install

      - name: Build project
        run: |
          cd sdk/medical-docs
          npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: sdk/medical-docs/dist
